### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by annastoilova** [tiki-bar/app#143]
As [**Darkbone** commenting in _Discord design feedback channel_], I want TIKI to have Dark mode, so that the experience is easier on my eyes.

Darkbone — 23/06/2021 
"_The colors were nice. It was easy for the eyes but I want to ask if you guys have a dark mode? I'm used to almost all of my apps having a dark mode, so it would nice if you guys have a dark mode as well."

Anna to design Dark Mode colour palette.
Potential inclusion in 0.2.2 or later. Not a priority.

**Comment by CraftingGamerTom** [comment]
@annastoilova Is the design spec open source? or can you share the color palette? Perhaps someone (or myself) can contribute to this
